export const sharedActions = {
	ACTIVE_LENS_DETAIL: 'ACTIVE_LENS_DETAIL',
    SEARCH_TERM_UPDATE: 'SEARCH_TERM_UPDATE',
    POPULATE_PHOTOS_DATA: 'POPULATE_PHOTOS_DATA',
    LOCAL_LENS_DATA: 'LOCAL_LENS_DATA'
};
